# Generated by Django 4.1.5 on 2023-02-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipuznik2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='skill_description',
            field=models.TextField(default=''),
        ),
    ]
