# Generated by Django 4.1.5 on 2023-02-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipuznik2', '0002_skills_skill_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='password',
            field=models.CharField(default='', max_length=256),
        ),
    ]
