# Generated by Django 4.1.5 on 2023-02-20 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipuznik2', '0003_worker_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('password', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipuznik2.skills')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipuznik2.user')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipuznik2.worker')),
            ],
        ),
    ]
