# Generated by Django 4.1.5 on 2023-03-02 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipuznik2', '0004_user_project'),
    ]

    operations = [
        migrations.RunSQL('DROP TABLE IF EXISTS shipuznik2_price;'),
    ]
