# Generated by Django 4.1.5 on 2023-03-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipuznik2', '0006_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
